# Generated by Django 3.0.2 on 2020-01-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campeao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('item1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item1', to='camp.Item')),
                ('item2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item2', to='camp.Item')),
                ('item3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item3', to='camp.Item')),
                ('item4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item4', to='camp.Item')),
                ('item5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item5', to='camp.Item')),
                ('item6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camp.Item')),
            ],
        ),
    ]
