# Generated by Django 3.0.2 on 2020-05-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_campeao_miniatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeao',
            name='titulo',
            field=models.CharField(default='Título', max_length=255),
        ),
    ]
