# Generated by Django 3.0.2 on 2020-05-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_campeao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='riot_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
