# Generated by Django 3.0.2 on 2020-05-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_item_riot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeao',
            name='item6',
        ),
        migrations.AddField(
            model_name='campeao',
            name='bota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bota', to='camp.Item'),
        ),
    ]
