# Generated by Django 3.0.2 on 2020-05-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_auto_20200503_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeao',
            name='miniatura',
        ),
    ]
