# Generated by Django 3.0.2 on 2020-05-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_remove_campeao_miniatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeao',
            name='inicial1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inicial1', to='camp.Item'),
        ),
        migrations.AddField(
            model_name='campeao',
            name='inicial2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inicial2', to='camp.Item'),
        ),
        migrations.AddField(
            model_name='campeao',
            name='inicial3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inicial3', to='camp.Item'),
        ),
    ]
