# Generated by Django 3.0.2 on 2020-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0008_auto_20200504_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(default='Sem Item', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='riot_id',
            field=models.CharField(default=3916, max_length=255),
        ),
    ]
