# Generated by Django 3.0 on 2020-06-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0011_auto_20200603_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeao',
            name='tipo',
            field=models.CharField(blank=True, default='Tipo', max_length=255),
        ),
    ]
