# Generated by Django 3.0 on 2020-06-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0012_campeao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='Spell', max_length=255)),
                ('desc', models.CharField(blank=True, default='Descrição', max_length=255)),
                ('spell_id', models.CharField(blank=True, default='id', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='campeao',
            name='espell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espell', to='camp.Spell'),
        ),
        migrations.AddField(
            model_name='campeao',
            name='qspell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qspell', to='camp.Spell'),
        ),
        migrations.AddField(
            model_name='campeao',
            name='rspell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rspell', to='camp.Spell'),
        ),
        migrations.AddField(
            model_name='campeao',
            name='wspell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wspell', to='camp.Spell'),
        ),
    ]
