# Generated by Django 3.0.2 on 2020-06-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0013_auto_20200618_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='spell_id',
            field=models.CharField(blank=True, default='id', max_length=100),
        ),
    ]
