# Generated by Django 3.0.8 on 2020-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0014_auto_20200619_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='video_link',
            field=models.CharField(blank=True, default='Link', max_length=255),
        ),
    ]
