# Generated by Django 3.0.8 on 2020-07-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0015_spell_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='video_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
